server:
  port : 8099



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssalMuck?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: wjdals12#
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jwt
  jwt:
    secret: oisadfjhvoasihjrdgoiahw34oihnoawedhnvoaijksd

  #redis
  redis:
    host: localhost
    port: 6379

  #swagger setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

